Repository moevm/mse1h2025-prog0, pull requests merged in 2025-03, with the labels that each got.

#31 feat: add CProgramRunner class (issue #14)
  src/prog_questions/utility/CProgramRunner.py
Labels: enhancement

#32 feat: add xml build system
  .gitignore
  README.md
  build/build.py
  build/template.xml
  requirements.txt
Labels: enhancement

#38 docs: add documentation for CProgramRunner
  README.md
Labels: documentation

#39 fix: update readme with windows symlinks guide
  README.md
Labels: bug

#47 feat: github actions tests
  .editorconfig
  .github/workflows/run-tests.yml
  .gitignore
  README.md
  build/build.py
  requirements.txt
  tests/QuestionSum_test.py
Labels: documentation, enhancement

#45 feat: add random condition loop wrapper
  requirements.txt
  src/prog_questions/QuestionRandomCondition.py
  src/prog_questions/__init__.py
  src/prog_questions/generators/__init__.py
  src/prog_questions/utility/__init__.py
Labels: enhancement

#51 feat: redo the execution error formation
  src/prog_questions/utility/CProgramRunner.py
Labels: enhancement

#52 docs: update the documentation of the CProgramRunner class
  README.md
Labels: documentation

#46 docs: add documentation for random condition wrapper
  README.md
Labels: documentation

#53 feat: add pytest to random condition wrapper
  src/prog_questions/__init__.py
  tests/QuestionRandomCondition_test.py
  tests/README.md
Labels: enhancement

#55 fix: add better description to random condition wrapper
  README.md
  src/prog_questions/QuestionRandomCondition.py
Labels: enhancement

#59 feat: implimentation QuestionStringOperations
  src/prog_questions/QuestionStringOperations.py
  src/prog_questions/__init__.py
Labels: enhancement

#44 feat: add random expression task
  .gitignore
  src/prog_questions/QuestionRandomExpression.py
  src/prog_questions/__init__.py
  tests/QuestionRandomExpression_test.py
Labels: enhancement

#62 Revert "feat: add random expression task"
  src/prog_questions/QuestionRandomExpression.py
Labels: bug

#61 feat: test string operations
  tests/QuestionStringOperations_test.py
Labels: enhancement

#65 fix: code runner strip problem
  src/prog_questions/QuestionStringOperations.py
Labels: bug

#67 fix: delete space noise
  src/prog_questions/QuestionStringOperations.py
Labels: bug

#68 fix: docs
  README.md
Labels: documentation

#69 fix: fix question names in xml files
  build/build.py
  src/prog_questions/QuestionBase.py
  src/prog_questions/QuestionRandomCondition.py
  src/prog_questions/QuestionRandomExpression.py
  src/prog_questions/QuestionStringOperations.py
Labels: bug

#70 docs: fix readme
  README.md
  tests/README.md
Labels: documentation

#71 docs: add presentation for iter 2
  Итерация 2 Презентация.pdf
Labels: documentation

#72 docs: update plans for 3rd iteration
  Итерация 2 Презентация.pdf
Labels: documentation
