Repository moevm/mse1h2025-prog0, pull requests merged in 2025-04, with the labels that each got.

#78 feat: add seed parameter to initTemplate
  README.md
  build/build.py
  src/prog_questions/QuestionBase.py
  tests/utility.py
Labels: enhancement

#77 feat: improve example text in question
  src/prog_questions/QuestionStringOperations.py
Labels: enhancement

#79 fix: make uniform task text for random condition
  src/prog_questions/QuestionRandomCondition.py
Labels: enhancement

#83 feat: wrap building in docker
  .github/images/success.png
  Dockerfile
  README.md
  build/build.py
Labels: documentation, enhancement

#88 feat: add comment metric
  src/prog_questions/utility/CommentMetric.py
  src/prog_questions/utility/__init__.py
Labels: enhancement

#89 feat: integrate comment metric
  README.md
  build/build.py
  build/template.xml
  src/prog_questions/QuestionBase.py
Labels: documentation, enhancement

#92 docs: add docs for comment metric
  README.md
Labels: documentation

#87 feat: add simple mode for random condition
  README.md
  src/prog_questions/QuestionRandomCondition.py
  tests/QuestionRandomCondition_test.py
Labels: documentation, enhancement

#91 docs: update tutorial
  README.md
Labels: documentation
