Repository moevm/mse1h2025-prog0, pull requests merged in 2025-05, with the labels that each got.

#94 feat: add simple solve for string operations
  README.md
  src/prog_questions/QuestionStringOperations.py
  tests/QuestionStringOperations_test.py
Labels: enhancement

#102 Update reports.md
  reports.md
Labels: documentation

#103 docs: add presentation 3
  Итерация 3 Презентация.pdf
Labels: documentation

#98 feat: add simple mode for random expression
  src/prog_questions/QuestionRandomExpression.py
  tests/QuestionRandomExpression_test.py
Labels: enhancement

#104 Docs: update random expression simple mode documentation
  README.md
Labels: documentation

#113 fix: handle decoding errors
  README.md
  src/prog_questions/utility/CProgramRunner.py
Labels: bug, documentation

#119 fix: add changes to QuestionBase interface
  README.md
  src/prog_questions/CustomQuestions.py
  src/prog_questions/QuestionBase.py
  src/prog_questions/__init__.py
  src/prog_questions/utility/CProgramRunner.py
  src/prog_questions/utility/__init__.py
Labels: enhancement

#120 fix: make timeout an execution error
  src/prog_questions/utility/CProgramRunner.py
  src/prog_questions/utility/__init__.py
Labels: bug

#122 docs: rework readme
  README.md
Labels: documentation

#125 Feat: improve string operations
  src/prog_questions/QuestionStringOperations.py
  tests/QuestionStringOperations_test.py
Labels: enhancement

#126 feat: add new tasks
  src/prog_questions/QuestionBase.py
  src/prog_questions/QuestionN1.py
  src/prog_questions/QuestionN2.py
  src/prog_questions/QuestionN3.py
  src/prog_questions/QuestionN5.py
  src/prog_questions/__init__.py
  tests/QuestionN1_test.py
  tests/QuestionN2_test.py
  tests/QuestionN3_test.py
  tests/QuestionN5_test.py
Labels: enhancement

#127 feat: improve random condition
  src/prog_questions/QuestionRandomCondition.py
  tests/QuestionRandomCondition_test.py
Labels: enhancement

#129 feat: add hint in task text
  src/prog_questions/QuestionRandomCondition.py
Labels: enhancement

#130 feat: add operation priority
  src/prog_questions/QuestionRandomExpression.py
Labels: enhancement

#131 docs: add presentation 4 iter
  reports.md
  Итерация 4 Презентация.pdf
Labels: documentation

#132 Develop to main merge iteration 4 end
  README.md
  src/prog_questions/CustomQuestions.py
  src/prog_questions/QuestionBase.py
  src/prog_questions/QuestionN1.py
  src/prog_questions/QuestionN2.py
  src/prog_questions/QuestionN3.py
  src/prog_questions/QuestionN5.py
  src/prog_questions/QuestionRandomCondition.py
  src/prog_questions/QuestionRandomExpression.py
  src/prog_questions/QuestionStringOperations.py
  src/prog_questions/__init__.py
  src/prog_questions/utility/CProgramRunner.py
  src/prog_questions/utility/__init__.py
  tests/QuestionN1_test.py
  tests/QuestionN2_test.py
  tests/QuestionN3_test.py
  tests/QuestionN5_test.py
  tests/QuestionRandomCondition_test.py
  tests/QuestionRandomExpression_test.py
  tests/QuestionStringOperations_test.py
Labels: enhancement
